### ISSUE TITLE
Close menu button not working on mobile view

### ISSUE THREAD

**Issue by jasoncardarelli** [jasoncardarelli/jasoncardarelli#35]
### Description
On the mobile view of the site, the close button of the menu is not working.

### Steps to reproduce bug
1. Navigate to [jasoncardarelli.com](https://jasoncardarelli.com) on any mobile device
2. Open the menu by clicking on the `Menu` icon button
3. Tap on the `Close` icon button and notice that the menu does not close

Note, on a computer while using a mouse or trackpad to navigate, clicking on the `Close` icon button causes the menu to flash closed and reopen again.

### Expected behavior
The menu should close once the `Close` icon button is tapped or clicked.

### Screenshots
<img src="https://github.com/jasoncardarelli/jasoncardarelli/assets/5059005/6691e2d8-56b2-4bb3-a538-631f5361ecea" width=50%>

**Comment by Sky-De** [comment]
@jasoncardarelli please assign this to me, i would like to fix this for you
Thanks
